### ISSUE TITLE
ROLES: Zusätzliche Rolle Kassier in allen Geschäftsstellen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_generic#19]
Aktuell gibt es im Generic Wagon keine Rolle mit finance Berechtigung.
Damit die Rechnungsstellung auch von Kunden im Generic Wagon genutzt werden kann, sollen in allen Geschäftsstellen eine Rolle "Kassier" mit berechtigungen für die eigene und darunterleigende Gruppen und finance berechtigung hinzugefügt werden.

- [x] In Geschäftsstelle unter  Hauptebene neue Rolle hinzufügen: Kassier: [:layer_and_below_full, :contact_data, :finance]
- [x] In Geschäftsstelle unter  Region/Kanton neue Rolle hinzufügen: Kassier: [:layer_and_below_full, :contact_data, :finance]
- [x] In Geschäftsstelle unter  Lokalgruppe/Sektion neue Rolle hinzufügen: Kassier: [:layer_and_below_full, :contact_data, :finance]

# Mockup

![grafik](https://github.com/hitobito/hitobito_generic/assets/100761305/c0c12bac-e8ba-4269-8fde-2358d9428da4)

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [x] Migration erstellen
- [x] Domainklasse erstellen oder anpassen
- [x] Model/View/Controller anpassen
- [x] Neues Feature mit FeatureGate deaktivierbar machen
- [x] Specs schreiben
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
